#!/usr/bin/env bash
set -euo pipefail

cmd=${1:-}
if [[ -z "${cmd}" ]]; then
  echo "Usage: scripts/db/run_goose.sh <up|down|redo|status>" >&2
  exit 2
fi

case "${cmd}" in
  up|down|redo|status) ;;
  *)
    echo "Unknown command: ${cmd}. Expected: up|down|redo|status" >&2
    exit 2
    ;;
esac

ROOT_DIR=$(git rev-parse --show-toplevel)
GOOSE_MIGRATIONS_DIR="${GOOSE_MIGRATIONS_DIR:-migrations/hrm}"
GOOSE_TABLE="${GOOSE_TABLE:-goose_db_version}"

if ! [[ "${GOOSE_TABLE}" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
  echo "Invalid GOOSE_TABLE: ${GOOSE_TABLE}. Expected /^[a-zA-Z_][a-zA-Z0-9_]*$/" >&2
  exit 2
fi

if [[ "${GOOSE_MIGRATIONS_DIR}" = /* ]]; then
  MIGRATIONS_DIR="${GOOSE_MIGRATIONS_DIR}"
else
  MIGRATIONS_DIR="${ROOT_DIR}/${GOOSE_MIGRATIONS_DIR}"
fi

if [[ ! -d "${MIGRATIONS_DIR}" ]]; then
  echo "Missing migrations directory: ${MIGRATIONS_DIR}" >&2
  exit 2
fi

DB_NAME=${DB_NAME:-iota_erp}
DB_USER=${DB_USER:-postgres}
DB_PASSWORD=${DB_PASSWORD:-postgres}
DB_HOST=${DB_HOST:-localhost}
DB_PORT=${DB_PORT:-5432}

DSN="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"

if ! command -v goose >/dev/null 2>&1; then
  echo "goose not found in PATH. Install it with: make goose-install" >&2
  exit 127
fi

if [[ -n "${GOOSE_VERSION_EXPECTED:-}" ]]; then
  goose_version_out=$(goose -version 2>&1 || true)
  if [[ "${goose_version_out}" != *"${GOOSE_VERSION_EXPECTED}"* ]]; then
    echo "goose version mismatch. expected=${GOOSE_VERSION_EXPECTED} actual=${goose_version_out}" >&2
    exit 2
  fi
fi

if [[ "${GOOSE_BOOTSTRAP_BASELINE:-0}" == "1" ]]; then
  if ! command -v psql >/dev/null 2>&1; then
    echo "psql not found in PATH (required for GOOSE_BOOTSTRAP_BASELINE=1)" >&2
    exit 127
  fi

  baseline_version=${GOOSE_BASELINE_VERSION:-1}
  if ! [[ "${baseline_version}" =~ ^[0-9]+$ ]]; then
    echo "GOOSE_BASELINE_VERSION must be a positive integer, got: ${baseline_version}" >&2
    exit 2
  fi

  PGPASSWORD="${DB_PASSWORD}" psql "${DSN}" -v ON_ERROR_STOP=1 <<SQL
DO \$\$
DECLARE
  goose_table text := '${GOOSE_TABLE}';
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = current_schema()
      AND tablename = goose_table
  ) THEN
    EXECUTE format(
      'CREATE TABLE %I (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        version_id bigint NOT NULL,
        is_applied boolean NOT NULL,
        tstamp timestamp NOT NULL DEFAULT now()
      )',
      goose_table
    );
  END IF;
END \$\$;

DO \$\$
DECLARE
  goose_table text := '${GOOSE_TABLE}';
BEGIN
  EXECUTE format(
    'INSERT INTO %I (version_id, is_applied)
     SELECT $1, true
     WHERE NOT EXISTS (
       SELECT 1 FROM %I WHERE version_id = $1 AND is_applied = true
     )',
    goose_table,
    goose_table
  )
  USING ${baseline_version}::bigint;
END \$\$;
SQL

  echo "Bootstrapped goose baseline version_id=${baseline_version} in ${DB_NAME}"
  exit 0
fi

goose_args=(
  -dir "${MIGRATIONS_DIR}"
  -table "${GOOSE_TABLE}"
  postgres
  "${DSN}"
  "${cmd}"
)

if [[ "${cmd}" == "down" || "${cmd}" == "redo" ]]; then
  if [[ -n "${GOOSE_STEPS:-}" ]]; then
    if ! [[ "${GOOSE_STEPS}" =~ ^[0-9]+$ ]]; then
      echo "GOOSE_STEPS must be a positive integer, got: ${GOOSE_STEPS}" >&2
      exit 2
    fi
    goose_args+=("${GOOSE_STEPS}")
  fi
fi

exec goose "${goose_args[@]}"
