name: iota-sdk-dev

services:
  db:
    image: postgres:17
    restart: always
    shm_size: "1g"
    command: [ "postgres", "-c", "max_connections=500" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iota_erp
    ports:
      - "${PG_PORT:-5438}:5432"
    volumes:
      - sdk-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - sdk-redis:/data

volumes:
  sdk-data:
  sdk-redis:
