FROM golang:1.24

WORKDIR /build

COPY scripts/install.sh .
RUN chmod +x install.sh && ./install.sh && go install github.com/a-h/templ/cmd/templ@v0.3.856

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.8

COPY go.mod go.sum ./
RUN go mod download
COPY . .

CMD ["sh", "-c", "go vet ./... && golangci-lint run ./... && go test -v ./..."]
