// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package changerequests_sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrgChangeRequestByID = `-- name: GetOrgChangeRequestByID :one
SELECT
    tenant_id,
    id,
    request_id,
    requester_id,
    status,
    payload_schema_version,
    payload,
    notes,
    created_at,
    updated_at
FROM
    org_change_requests
WHERE
    tenant_id = $1
    AND id = $2
`

type GetOrgChangeRequestByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetOrgChangeRequestByID(ctx context.Context, arg GetOrgChangeRequestByIDParams) (OrgChangeRequest, error) {
	row := q.db.QueryRow(ctx, getOrgChangeRequestByID, arg.TenantID, arg.ID)
	var i OrgChangeRequest
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.RequestID,
		&i.RequesterID,
		&i.Status,
		&i.PayloadSchemaVersion,
		&i.Payload,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgChangeRequestByRequestID = `-- name: GetOrgChangeRequestByRequestID :one
SELECT
    tenant_id,
    id,
    request_id,
    requester_id,
    status,
    payload_schema_version,
    payload,
    notes,
    created_at,
    updated_at
FROM
    org_change_requests
WHERE
    tenant_id = $1
    AND request_id = $2
`

type GetOrgChangeRequestByRequestIDParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	RequestID string      `json:"request_id"`
}

func (q *Queries) GetOrgChangeRequestByRequestID(ctx context.Context, arg GetOrgChangeRequestByRequestIDParams) (OrgChangeRequest, error) {
	row := q.db.QueryRow(ctx, getOrgChangeRequestByRequestID, arg.TenantID, arg.RequestID)
	var i OrgChangeRequest
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.RequestID,
		&i.RequesterID,
		&i.Status,
		&i.PayloadSchemaVersion,
		&i.Payload,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrgChangeRequests = `-- name: ListOrgChangeRequests :many
SELECT
    tenant_id,
    id,
    request_id,
    requester_id,
    status,
    payload_schema_version,
    payload,
    notes,
    created_at,
    updated_at
FROM
    org_change_requests
WHERE
    tenant_id = $1
    AND ($2::text = '' OR status = $2)
    AND (
        $3::timestamptz IS NULL
        OR $4::uuid IS NULL
        OR (updated_at, id) < ($3::timestamptz, $4::uuid)
    )
ORDER BY
    updated_at DESC, id DESC
LIMIT $5
`

type ListOrgChangeRequestsParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Column2  string             `json:"column_2"`
	Column3  pgtype.Timestamptz `json:"column_3"`
	Column4  pgtype.UUID        `json:"column_4"`
	Limit    int32              `json:"limit"`
}

func (q *Queries) ListOrgChangeRequests(ctx context.Context, arg ListOrgChangeRequestsParams) ([]OrgChangeRequest, error) {
	rows, err := q.db.Query(ctx, listOrgChangeRequests,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgChangeRequest{}
	for rows.Next() {
		var i OrgChangeRequest
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.RequestID,
			&i.RequesterID,
			&i.Status,
			&i.PayloadSchemaVersion,
			&i.Payload,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrgChangeRequestDraftByID = `-- name: UpdateOrgChangeRequestDraftByID :one
UPDATE org_change_requests
SET
    payload = $3,
    notes = $4,
    updated_at = now()
WHERE
    tenant_id = $1
    AND id = $2
    AND status = 'draft'
RETURNING
    tenant_id, id, request_id, requester_id, status, payload_schema_version, payload, notes, created_at, updated_at
`

type UpdateOrgChangeRequestDraftByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	Payload  []byte      `json:"payload"`
	Notes    *string     `json:"notes"`
}

func (q *Queries) UpdateOrgChangeRequestDraftByID(ctx context.Context, arg UpdateOrgChangeRequestDraftByIDParams) (OrgChangeRequest, error) {
	row := q.db.QueryRow(ctx, updateOrgChangeRequestDraftByID,
		arg.TenantID,
		arg.ID,
		arg.Payload,
		arg.Notes,
	)
	var i OrgChangeRequest
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.RequestID,
		&i.RequesterID,
		&i.Status,
		&i.PayloadSchemaVersion,
		&i.Payload,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrgChangeRequestStatusByID = `-- name: UpdateOrgChangeRequestStatusByID :one
UPDATE org_change_requests
SET
    status = $3,
    updated_at = now()
WHERE
    tenant_id = $1
    AND id = $2
RETURNING
    tenant_id, id, request_id, requester_id, status, payload_schema_version, payload, notes, created_at, updated_at
`

type UpdateOrgChangeRequestStatusByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateOrgChangeRequestStatusByID(ctx context.Context, arg UpdateOrgChangeRequestStatusByIDParams) (OrgChangeRequest, error) {
	row := q.db.QueryRow(ctx, updateOrgChangeRequestStatusByID, arg.TenantID, arg.ID, arg.Status)
	var i OrgChangeRequest
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.RequestID,
		&i.RequesterID,
		&i.Status,
		&i.PayloadSchemaVersion,
		&i.Payload,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrgChangeRequest = `-- name: UpsertOrgChangeRequest :one
INSERT INTO org_change_requests (tenant_id, request_id, requester_id, status, payload_schema_version, payload, notes)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, request_id)
    DO UPDATE SET
        requester_id = EXCLUDED.requester_id, status = EXCLUDED.status, payload_schema_version = EXCLUDED.payload_schema_version, payload = EXCLUDED.payload, notes = EXCLUDED.notes, updated_at = now()
    RETURNING
        tenant_id, id, request_id, requester_id, status, payload_schema_version, payload, notes, created_at, updated_at
`

type UpsertOrgChangeRequestParams struct {
	TenantID             pgtype.UUID `json:"tenant_id"`
	RequestID            string      `json:"request_id"`
	RequesterID          pgtype.UUID `json:"requester_id"`
	Status               string      `json:"status"`
	PayloadSchemaVersion int32       `json:"payload_schema_version"`
	Payload              []byte      `json:"payload"`
	Notes                *string     `json:"notes"`
}

func (q *Queries) UpsertOrgChangeRequest(ctx context.Context, arg UpsertOrgChangeRequestParams) (OrgChangeRequest, error) {
	row := q.db.QueryRow(ctx, upsertOrgChangeRequest,
		arg.TenantID,
		arg.RequestID,
		arg.RequesterID,
		arg.Status,
		arg.PayloadSchemaVersion,
		arg.Payload,
		arg.Notes,
	)
	var i OrgChangeRequest
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.RequestID,
		&i.RequesterID,
		&i.Status,
		&i.PayloadSchemaVersion,
		&i.Payload,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
