// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: commands.sql

package position_sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (tenant_id, name, description)
    VALUES ($1, $2, $3)
RETURNING
    id
`

type CreatePositionParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPosition, arg.TenantID, arg.Name, arg.Description)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deletePosition = `-- name: DeletePosition :exec
DELETE FROM positions
WHERE id = $1
    AND tenant_id = $2
`

type DeletePositionParams struct {
	ID       int32       `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeletePosition(ctx context.Context, arg DeletePositionParams) error {
	_, err := q.db.Exec(ctx, deletePosition, arg.ID, arg.TenantID)
	return err
}

const updatePosition = `-- name: UpdatePosition :exec
UPDATE
    positions
SET
    name = $1,
    description = $2
WHERE
    id = $3
    AND tenant_id = $4
`

type UpdatePositionParams struct {
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	ID          int32       `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) error {
	_, err := q.db.Exec(ctx, updatePosition,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.TenantID,
	)
	return err
}
